- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install nbconvert


- name: Run TTC prediction notebook
  run: |
    jupyter nbconvert --to notebook --execute weekly_prediction.ipynb --output executed_weekly_prediction.ipynb


- name: Commit prediction output
  run: |
    git config user.name github-actions
    git config user.email github-actions@github.com

    git add output/predicted_dataset.parquet

    git diff --cached --quiet || git commit -m "Daily TTC prediction update"

    git push